### ISSUE TITLE
Enable Upload of Floor-plans

### ISSUE THREAD

**Issue by Benmoony** [Benmoony/library_app#56]
Implement The ability to upload floor-plans

**Comment by emott10** [comment]
The user can now upload a new floor-plan to the site

**Comment by emott10** [comment]
I have reopened this issue because SpaceUse uses SVG's as the floor-plan and after doing research I found that user uploaded svg files cause a huge security risk for the site, looking into work arounds.

**Comment by emott10** [comment]
User can now upload svg images
